<#-- Hello World Template -->
<#-- Generated by ProMarker MiRel Stencil Engine -->
<#assign greeting = (language == "ja")?then("こんにちは", "Hello")>
<#assign message = (language == "ja")?then("さん、ProMarker MiRel へようこそ！", ", Welcome to ProMarker MiRel!")>
${greeting} ${userName}${message}

<#if language == "ja">
このファイルは MiRel のステンシル機能によって生成されました。
ステンシルを使用することで、繰り返し使用するコードやドキュメントのテンプレートを効率的に管理できます。

ステンシル設定:
- ステンシル名: ${.data_model.stencilName!"hello-world"}
- テンプレート名: hello
- 生成日時: ${.now?string("yyyy-MM-dd HH:mm:ss")}
<#else>
This file was generated by MiRel's stencil feature.
Using stencils, you can efficiently manage templates for repeatedly used code and documents.

Stencil Configuration:
- Stencil Name: ${.data_model.stencilName!"hello-world"}  
- Template Name: hello
- Generated: ${.now?string("yyyy-MM-dd HH:mm:ss")}
</#if>

<#-- パラメータ情報 -->
Parameters Used:
- userName: ${userName}
- language: ${language}