# application-dev.yml
spring:
  datasource:
    url: jdbc:h2:file:./data/mireldb;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;MODE=LEGACY
    driver-class-name: org.h2.Driver
    username: sa
    password:
  session:
    jdbc:
      schema: classpath:org/springframework/session/jdbc/schema-h2.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        hbm2ddl:
          halt_on_error: false
    show-sql: false

mirel:
  storage-dir: ./data/storage