###################################################################
# Stencil settings.
###################################################################
# Sample Stencil: hello-world
# Simple Hello World generator for immediate developer onboarding experience
stencil:
  config:
    categoryId: "/samples"
    categoryName: "Sample Stencils"
    id: "/samples/hello-world"
    name: "Hello World Generator"
    serial: "250913A"
    lastUpdate: "2025/09/13"
    lastUpdateUser: "mirelplatform"
    description: |
      シンプルなHello Worldジェネレーターです。
      自動生成ソリューションのサンプルとして、最小限の生成結果を確認できます。
  dataElement:
    - id: "message"
  dataDomain:
    - id: "message"
      name: "メッセージ"
      value: "Hello, World!"
      type: "text"
      placeholder: "メッセージを入力してください"
      note: "テンプレートで使用されるメッセージです。"
  codeInfo:
    copyright: Copyright(c) 2025 mirelplatform.
    versionNo: "1.0"
    author: mirelplatform
    vendor: mirelplatform